apiVersion: v1
kind: Service
metadata:
  name: flight-booking-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: flight-booking-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
