apiVersion: v1
kind: Service
metadata:
  name: react-vite-service
spec:
  type: LoadBalancer # Use LoadBalancer for external access
  selector:
    app: react-vite
  ports:
    - protocol: TCP
      port: 80 # Exposes port 80 to the outside world
      targetPort: 80 # Port where NGINX is running inside the container
