name: Deploy flight-booking-frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1 # Specify version
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="${{ github.sha }}"
          docker build --no-cache --build-arg VITE_BASE_URL=${{ secrets.VITE_BASE_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/flight-booking-frontend:${IMAGE_TAG} \
            -t ${{ secrets.DOCKER_USERNAME }}/flight-booking-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flight-booking-frontend:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/flight-booking-frontend:latest

      - name: Update Kubernetes deployment
        run: |
          # Get current timestamp
          TIMESTAMP=$(date +%s)

          # Update the image tag in deployment file
          sed -i "s|kubectl.kubernetes.io/restartedAt:.*|kubectl.kubernetes.io/restartedAt: '$TIMESTAMP'|" k8s/flight-booking-frontend-deployment.yaml
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/flight-booking-frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/flight-booking-frontend:${{ github.sha }}|' k8s/flight-booking-frontend-deployment.yaml

          # Apply the changes
          kubectl apply -f k8s/flight-booking-frontend-deployment.yaml
          kubectl apply -f k8s/flight-booking-frontend-service.yaml

      - name: Force rollout restart
        run: |
          kubectl rollout restart deployment flight-booking-frontend-deployment
          kubectl rollout status deployment flight-booking-frontend-deployment
